spring.application.name=taskmanager
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:taskdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=task
spring.datasource.password=task123
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.settings.web-allow-others=true
# Telling Spring to initialize the database using schema and data SQL files
spring.sql.init.mode=always

# Since we are using Hibernate, we want it to validate our schema.sql rather than trying to create its own and clashing
spring.jpa.hibernate.ddl-auto=validate

# ensure timestamps are handled correctly in H2
spring.jpa.properties.hibernate.jdbc.time_zone=UTC